### ISSUE TITLE
Add bioschemas markup for ingestion to TeSS

### ISSUE THREAD

**Issue by foreveremain** [sib-swiss/training-collection#13]
It would be great if the html version were enhanced with bioschemas annotation so content can be automatically indexed via TeSS:

"Structured Data Types"
 https://tess.elixir-europe.org/about/registering#:~:text=Structured%20Data%20Types

**Comment by foreveremain** [comment]
This is almost certainly feasible with custom rendering templates but may complicate authoring guidelines.

**Comment by GeertvanGeest** [comment]
It would be great to have these materials automatically indexed via TeSS, but it's hard for me to estimate how much work that would require from our side. Would each resource in this repo have to be described? 
It has some value that the content of this repository currently is 'low level' (i.e. adding material only requires a line of markdown), making it transparent and easier for people to get involved. 
Would it be an alternative to encourage developers of training material to add the bioschemas information to their repository or to their gh-page (e.g.: https://bioschemas.org/tutorials/howto/howto_add_github)? Happy to hear your opinion on this!

**Comment by foreveremain** [comment]
I agree there's work invovled - Material developers are certainly being encouraged - but everything is still rather new, so not many people are doing it yet (except, of course, for the pilot projects working with bioschemas ;) ). I guess a bot could be developed to push PRs to all sites.. might be a fun biohackathon project for someone !

For reference, the TeSS bioschemas scraper will look for pages conforming to the TrainingMaterials profile: https://bioschemas.org/profiles/TrainingMaterial/0.9-DRAFT-2020_12_08

**Comment by GeertvanGeest** [comment]
Web version of this list is not coming soon, so closing for now.
