### ISSUE TITLE
SPHN Training material

### ISSUE THREAD

**Issue by jarmida** [sib-swiss/training-collection#60]
Hi Geert. Here is the current list of SPHN Training material:

- [**SIB SPHN** Querying Data with SPARQL](https://git.dcc.sib.swiss/sphn-semantic-framework/sphn-training-material/-/tree/master/Querying%20Data%20with%20SPARQL#querying-data-with-sparql) | [website](https://sphn.ch/training/querying-data-with-sparql/#)
- [**SIB SPHN** How to use Python and R with RDF Data](https://git.dcc.sib.swiss/sphn-semantic-framework/sphn-training-material/-/tree/master/How%20to%20use%20Python%20and%20R%20with%20RDF%20data#how-to-use-python-and-r-with-rdf-data) | [website](https://sphn.ch/training/pythonandr/)
- [**SIB SPHN** Validate Graph Data with SHACL](https://git.dcc.sib.swiss/sphn-semantic-framework/sphn-training-material/-/tree/master/Validate%20Graph%20Data%20with%20SHACL#validate-graph-data-with-shacl) | [website](https://sphn.ch/validate-graph-data-with-shacl/)
- [**SIB SPHN** RDF Schema and Data Visualization](https://git.dcc.sib.swiss/sphn-semantic-framework/sphn-training-material/-/tree/master/RDF%20Schema%20and%20Data%20Visualization%20Training#rdf-schema-and-data-visualization-training) | [website](https://sphn.ch/training/datavisualization/)
- [**SIB SPHN** Semantic Standards](https://git.dcc.sib.swiss/sphn-semantic-framework/sphn-training-material/-/tree/master/Semantic%20Standards#semantic-standards) | [website](https://sphn.ch/training/semantic-standards-training/)
- [**SIB SPHN** Training Primer (RDF and SPARQL)](https://git.dcc.sib.swiss/sphn-semantic-framework/sphn-training-material/-/tree/master/SPHN%20RDF%20and%20SPARQL%20primer#training-primer-rdf-and-sparql) | [website](https://sphn.ch/training/sphn-rdf-training-primer/)
- [**SIB SPHN** Expanding the SPHN RDF Schema](https://git.dcc.sib.swiss/sphn-semantic-framework/sphn-training-material/-/tree/master/Expanding%20the%20SPHN%20RDF%20Schema#expanding-the-sphn-rdf-schema) | [website](https://sphn.ch/training/protege-training/)
- [**SIB SPHN** FAIR principles in practice for health data](https://git.dcc.sib.swiss/sphn-semantic-framework/sphn-training-material/-/tree/master/FAIR%20principles%20in%20practice%20for%20health%20data) | [website](https://sphn.ch/training/fair-principles-in-practice-for-health-data/)
- [**SIB SPHN** How to create a concept for the SPHN Dataset](https://git.dcc.sib.swiss/sphn-semantic-framework/sphn-training-material/-/tree/master/How%20to%20create%20concepts%20for%20the%20SPHN%20Dataset#how-to-create-a-concept-for-the-sphn-dataset) | [website](https://sphn.ch/training/create-a-concept-for-sphn-dataset/)

**Comment by GeertvanGeest** [comment]
Hi Jan,

Thanks! It's really a cool extensive resource.
Because at a later stage we want to be able to use the github/lab REST APIs to retrieve additional information, each line in the list is expected to be a single repository, so for this material it would be:

```
- [**SIB SPHN** SPHN Training material](https://git.dcc.sib.swiss/sphn-semantic-framework/sphn-training-material/) | [website](https://sphn.ch/training/)
```

Is that okay? I'm planning to add it to **Reproducibility and data management** > **Data management**.

**Comment by jarmida** [comment]
Yes no problem we can go with SIB SPHN. In that case I will modify the titles and get rid of the SPHN (it wasn't originally there).

The section seems fine, I will just double check with the other!

**Comment by jarmida** [comment]
Hi Geert, would something like this work for the institution part?

[**SIB Personalized Health informatics Group** SPHN Training material](https://git.dcc.sib.swiss/sphn-semantic-framework/sphn-training-material/) | [website](https://sphn.ch/training/)
