### ISSUE TITLE
Add GIT Tutorial

### ISSUE THREAD

**Issue by BioinfGuru** [sib-swiss/training-collection#81]
Hi there,

I've put together a learning resource on GitHub for git beginners at:

[BioinfGuru/gitTutorial](https://github.com/BioinfGuru/gitTutorial)

It would be useful for those teaching a git beginner's course, or for anyone needing a step by step introduction to GIT Version Control. It provides a walkthrough with commands for the following basics from install to problem solving:

1 - Install and setup GIT
2 - Connect to GitHub
3 - Create your first local repository
4 - Create a gitignore file
5 - Make your first commit
6 - Clone your first remote repository
7 - Branching & Merging
8 - Merge conflicts
9 - Fixing common problems
10 - Quick Start Guide

To be clear, all I've done here is put the many tutorials out there, into one walk-through. The credit for this goes to those that put the original work together in the form of many youtube and online tutorials/documents. I just put together a kind of one-stop-shop to get someone started without having to trawl through google searches/git documents.

Regards,
Kenneth

**Comment by GeertvanGeest** [comment]
I added it to [glittr.org](https://glittr.org). Starting today, glittr will be place to add courses. This collection will be updated based on the content of glittr.org.
